name: "Podcast Generator"
author: "marius Ronning"
description: "Generates a feed for a podcast from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    description: The commiters email adress
    required: true
    default: ${{github.actor}}@localhost
  name:
    description: the commiters name 
    required: true
    default : ${{githun.actor }}